Spring.application.name=devshowcase

# Configuração da Base de Dados PostgreSQL no Render
spring.datasource.url=jdbc:postgresql://dpg-daqr6549v7es73fqlmv0-a.oregon-postgres.render.com:5432/devshowcase_db_xcei?user=devshowcase_db_xcei_user&password=qwE3hsPwdXA0p3VQsTrIk5dzBPerkr9z
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
